title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
baseurl: ""
url: "https://mohi.hotelitalia.com.ec"

# Theme settings
theme: just-the-docs
color_scheme: light

# Navigation settings
nav:
  - title: Inicio
    url: /
    nav_order: 1
  - title: Gerencia
    url: /gerencia/
    nav_order: 2
    children:
      - title: Estrategia
        url: /gerencia/estrategia/
      - title: Organigrama
        url: /gerencia/organigrama/
      - title: Políticas
        url: /gerencia/politicas/
      - title: Reuniones
        url: /gerencia/reuniones/
  - title: Departamentos
    url: /departamentos/
    nav_order: 3
    children:
      - title: Administración
        url: /departamentos/administracion/
      - title: Cocina
        url: /departamentos/cocina/
      - title: Contabilidad
        url: /departamentos/contabilidad/
      - title: Housekeeping
        url: /departamentos/housekeeping/
      - title: Mantenimiento
        url: /departamentos/mantenimiento/
      - title: Recepción
        url: /departamentos/recepcion/
      - title: Restaurante
        url: /departamentos/restaurante/
  - title: Recursos
    url: /recursos/
    nav_order: 4
    children:
      - title: Formularios
        url: /recursos/formularios/
      - title: Metodología
        url: /recursos/metodologia/
        children:
          - title: Holacracy
            url: /recursos/metodologia/holacracy/
          - title: Lean
            url: /recursos/metodologia/lean/
          - title: OKR
            url: /recursos/metodologia/okr/
      - title: Procesos
        url: /recursos/procesos/
      - title: Reportes
        url: /recursos/reportes/
      - title: Sistemas
        url: /recursos/sistemas/
      - title: Manuales
        url: /recursos/manuales/

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 Hotel Italia"

plugins:
  - jekyll-seo-tag