title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
baseurl: "/MOHI"
url: "https://santiago8781.github.io"

# Theme settings
theme: just-the-docs
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024 Hotel Italia"

plugins:
  - jekyll-seo-tag