title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
baseurl: ""
url: "https://mohi.hotelitalia.com.ec"

# Theme settings
theme: just-the-docs
color_scheme: italia  # Using our custom color scheme

# Logo settings
logo: "/assets/images/hi_logo.png"  # Corrected hyphen in filename
nav_logo:
  height: "150px"
  width: "auto"
  padding: "1.5rem"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 Hotel Italia"

plugins:
  - jekyll-seo-tag