title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
baseurl: ""
url: "https://mohi.hotelitalia.com.ec"

# Theme settings
theme: just-the-docs
color_scheme: light

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable or disable the site search
search_enabled: true

# Sort order for navigation links
nav_sort: case_sensitive

# External navigation links
nav_external_links: []

# Footer content
footer_content: "Copyright &copy; 2025 Hotel Italia"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme
color_scheme: light

plugins:
  - jekyll-seo-tag