title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
baseurl: ""
url: "https://mohi.hotelitalia.com.ec"

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: light

# Auxiliary links
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable search
search_enabled: true

# Enable copy button on code blocks
enable_copy_code_button: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2025 Hotel Italia"