title: Marco Operativo Hotel Italia (MOHI)
description: Sistema Integrado de Gestión Hotelera
theme: just-the-docs

url: https://santiago8781.github.io
baseurl: "/MOHI"

# Theme settings
logo: "/assets/images/hi-logo.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: italia

# Search
search_enabled: true
search:
  heading_level: 4
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: true

# Navigation
nav_external_links:
  - title: Hotel Italia Website
    url: https://hotelitalia.com.ec
    hide_icon: false

# Aux links
aux_links:
  "MOHI en GitHub":
    - "//github.com/santiago8781/MOHI"

# Footer
footer_content: "© 2024 Hotel Italia - Cuenca, Ecuador"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Back to top link
back_to_top: true
back_to_top_text: "Volver arriba"